# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Vite app to Azure Web App - quiz-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-app
          path: frontend/dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_069A047662374742A21A6DC60FC764AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD343BE13EAB49C3BA970F88250C8977 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67035275A9224FADA5FD679C10751E10 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: quiz-frontend
          slot-name: Production
          package: frontend/dist
